/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
import javax.swing.*;
public class Timer extends javax.swing.JPanel implements Runnable
{

    /**
     * Creates new form Timer
     */
    
    public Timer() {
        Thread t=new Thread(this);
        t.start();
        initComponents();
    }
    @Override
    public void run()
    {
        int secs=0;
        int mins=4;
        while(mins>0)
        {
            mins--;
            secs=59;
            while(secs>=0)
            {
                try
                {
                    Thread.sleep(100);
                }
                catch(InterruptedException e)
                {

                }
                timer.setText(mins+":"+secs);
//                tobj.timer.setText(mins+":"+secs);
                //System.out.println(mins+":"+secs);
                secs--;
            } 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
